version: "3.8"

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
    environment:
      - PORT
      - MONGO_URI
      - PG_URI
      - DB_TYPE
    depends_on:
      - mongo
      - postgres

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  mongo_data:
  pg_data:
